# Generated by Django 5.2.5 on 2025-09-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevices',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
