# Generated by Django 5.2.5 on 2025-09-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0002_sevices_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevices',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
