# Generated by Django 5.2.5 on 2025-09-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0003_alter_sevices_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sevices',
            new_name='Services',
        ),
    ]
