# Generated by Django 5.2.5 on 2025-09-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0004_rename_sevices_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
