# Generated by Django 5.2.5 on 2025-09-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0005_alter_services_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='services',
            name='time_create',
            field=models.DateTimeField(default='2025-09-08 15:34'),
        ),
        migrations.AddField(
            model_name='services',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
