# Generated by Django 5.2.5 on 2025-09-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0006_services_slug_services_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
