# Generated by Django 5.2.5 on 2025-09-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0007_alter_services_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
