# Generated by Django 5.2.5 on 2025-09-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0008_alter_services_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='availability',
            field=models.BooleanField(choices=[(0, 'Услуга не доступна'), (1, 'Услуга доступна')], default=1),
        ),
    ]
