# Generated by Django 5.2.5 on 2025-09-09 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0009_alter_services_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Voka.direction'),
        ),
    ]
