# Generated by Django 5.2.5 on 2025-09-09 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0010_direction_services_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Voka.direction'),
        ),
    ]
