# Generated by Django 5.2.5 on 2025-09-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0012_doctors_alter_services_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Стаж работы'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
