# Generated by Django 5.2.5 on 2025-09-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0013_create_appointment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Стаж работы'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='services',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services', to='Voka.doctors'),
        ),
    ]
