# Generated by Django 5.2.5 on 2025-09-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0013_doctors_experience_doctors_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services', to='Voka.doctors'),
        ),
    ]
