# Generated by Django 5.2.5 on 2025-09-30 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0014_doctors_experience_doctors_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='on_sale',
            field=models.IntegerField(choices=[(0, 'Скидка'), (1, 'Скидки нет')], default=1, verbose_name='На акции'),
        ),
        migrations.AlterField(
            model_name='services',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Voka.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='services',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services', to='Voka.doctors', verbose_name='Время создания'),
        ),
    ]
