# Generated by Django 5.2.5 on 2025-09-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0015_services_on_sale_alter_services_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='sale_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер скидки'),
        ),
    ]
