# Generated by Django 5.2.5 on 2025-09-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0016_services_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='manаger',
            field=models.IntegerField(choices=[(0, 'Не входит в руководство'), (1, 'Входит в руководство')], default=0, verbose_name='Руководство'),
        ),
        migrations.AlterField(
            model_name='services',
            name='on_sale',
            field=models.IntegerField(choices=[(0, 'Скидки нет'), (1, 'Скидка')], default=0, verbose_name='На акции'),
        ),
    ]
