# Generated by Django 5.2.5 on 2025-09-30 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0017_doctors_manаger_alter_services_on_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='manаger',
            new_name='manager',
        ),
    ]
