# Generated by Django 5.2.5 on 2025-10-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0019_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, default='services/default.jpg', null=True, upload_to='services/'),
        ),
    ]
