# Generated by Django 5.2.5 on 2025-10-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0020_services_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.ImageField(blank=True, default='doctors/default.jpg', null=True, upload_to='doctors/'),
        ),
    ]
