# Generated by Django 5.2.5 on 2025-10-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0024_alter_order_service_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название новости')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('content', models.CharField(max_length=255, verbose_name='Контент новости')),
            ],
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Форма записи на прием', 'verbose_name_plural': 'Формы записи на прием'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Запись на прием', 'verbose_name_plural': 'Записи на прием'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
