# Generated by Django 5.2.5 on 2025-10-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0025_news_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
