# Generated by Django 5.2.5 on 2025-10-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0026_news_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новосоти'},
        ),
    ]
