# Generated by Django 5.2.5 on 2025-10-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0028_alter_news_options_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='news/default.jpg', null=True, upload_to='news/'),
        ),
    ]
