# Generated by Django 5.2.5 on 2025-10-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0029_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=555, verbose_name='Контент новости'),
        ),
    ]
