# Generated by Django 5.2.5 on 2025-10-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0030_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=1500, verbose_name='Контент новости'),
        ),
    ]
