# Generated by Django 5.2.5 on 2025-10-14 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0031_alter_news_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_name_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Имя пациента'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name_ru',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Имя пациента'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_surname_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Фамилия пациента'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_surname_ru',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Фамилия пациента'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='Причина визита'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Причина визита'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='job_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='job_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='patronymic_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='patronymic_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='surname_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='surname_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.CharField(max_length=1500, null=True, verbose_name='Контент новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.CharField(max_length=1500, null=True, verbose_name='Контент новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Название новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название новости'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Voka.services', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Voka.services', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='services',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='services',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='services',
            name='direction_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Voka.direction', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='services',
            name='direction_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Voka.direction', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Услуга'),
        ),
    ]
