# Generated by Django 5.2.5 on 2025-10-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0032_appointment_patient_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_en',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_ru',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_en',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_ru',
        ),
        migrations.RemoveField(
            model_name='services',
            name='direction_en',
        ),
        migrations.RemoveField(
            model_name='services',
            name='direction_ru',
        ),
        migrations.AddField(
            model_name='direction',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
