# Generated by Django 5.2.5 on 2025-10-17 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0035_cleanup_doctor_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'time')},
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='Voka.doctors', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='Voka.doctors', verbose_name='Врач'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'time'), ('doctor_en', 'date', 'time'), ('doctor_ru', 'date', 'time')},
        ),
    ]
