# Generated by Django 5.2.5 on 2025-10-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0037_doctors_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('new', 'В обработке'), ('confirmed', 'Подтверждена'), ('canceled', 'Отменена'), ('done', 'Завершена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
