# Generated by Django 5.2.5 on 2025-10-18 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0039_alter_appointment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Voka.doctors'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Voka.doctors'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Voka.doctors'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Voka.services'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
