# Generated by Django 5.2.5 on 2025-10-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voka', '0040_alter_appointment_doctor_alter_appointment_doctor_en_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'time')},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_en',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_ru',
        ),
    ]
